### ISSUE TITLE
mark an email as "read"

### ISSUE THREAD

**Issue by Que20** [chirag04/mail-listener2#16]
Is there a way to mark an email as "read" ?

**Comment by chickenCabbage** [comment]
I tried to mark an email as unseen using this piece:
```
mailListener.imap.addFlags(attributes.uid, 'UNSEEN', function(err) {
	if(!err) console.log('mail marked as unread');
	else throw err;
});
```
It does not recognize any flag that I gave it. I tried 'Unseen', '(Unseen)', '(\Unseen)', and '\(Unseen)' with different capital letter variations, none worked.
