### ISSUE TITLE
Listener disconnects

### ISSUE THREAD

**Issue by ghost** [chirag04/mail-listener2#8]
We are using Gmail(IMAP) to listen for emails in our application and it seems the listener disconnects at times.

Can you tell me what could the reason be if it has to do with code ?

We are listening for all events and our main application does not crash, only the listener disconnects.

Plus, if there a way to reconnect ? Sort of a container I can run listener inside that makes sure it reconnects when it disconnects ?

**Comment by BlueDevil2k6** [comment]
Hi. I am now running into the exact same thing, but it appears that the IMAP connect never gets re-established:

  mailListener.on("server:connected", function(){
    console.log("INFO: IMAP Server Connected");
  });

  mailListener.on("server:disconnected", function(){
    console.log("INFO: IMAP Server Disconnected");
    // Reconnect
    mailListener.start();
    console.log("INFO: Restarting IMAP connection");
  });

I see that the disconnection happens in the logs, but then it never reconnects. Got any suggestions?

**Comment by chirag04** [comment]
@BlueDevil2k6 follow @pwldp's answer or https://gist.github.com/developernoman/9031636

**Comment by BlueDevil2k6** [comment]
I'm doing exactly this, but it is not working. Now I'm starting to wonder
if there's something my PaaS provider (OpenShift) is doing to terminate the
ports and causing the reconnect to not work.

**Comment by chirag04** [comment]
it could be that. I'm not sure what can be done here. Let me know if you find anything.

**Comment by qadirsuh** [comment]
@chirag04 your link not working. please check

**Comment by anismulla02** [comment]
@chirag04 the link seems removed. please check
